# Generated by Django 3.2 on 2021-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='display',
            field=models.CharField(max_length=255, verbose_name='Тип дисплея'),
        ),
    ]
