# Generated by Django 3.2 on 2021-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210510_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон'),
        ),
    ]
