# Generated by Django 3.2.2 on 2021-05-23 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210521_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='feature',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 4, 59, 37, 492571, tzinfo=utc), verbose_name='Дата получения заказа'),
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeatureValidators',
        ),
    ]
